app:
  name: tiklab-xcode

APP_HOME: ${APP_HOME}
application: xcode

server:
  port: 8090

spring:
  freemarker:
    checkTemplateLocation: false

xcode:
  ssh:
    port: 10001
    key: tiklab-xcode-starter\file\id_rsa
  file: tiklab-xcode-starter\file

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_xcode?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  embbed:
    enable: false
  database: tiklab_xcode

eas:
  embbed:
    enable: true

#plugin config
DATA_HOME: ${user.home}/tiklab/${app.name}
plugin:
  path: ${DATA_HOME}/plugin

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: true
    port: 5001
    datapath: ${DATA_HOME}/data
  client:
    url: 127.0.0.1:5001
    group: g1
    database: dcs1
    expire: 600

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

datapath: ${DATA_HOME}/caches

message:
  sms:
    enabled: true


#    enable: false
#  address: http://192.168.10.14:8080
#  web:
#    address: http://192.168.10.14:3003

base:
  url: http://eas-ce.dev.tiklab.net



#homes
homes:
  address: http://192.168.10.7:8080

#license


#file
file:
  path: http://file.dev.tiklab.net


repository:
  address: ${DATA_HOME}/repository
backup:
  address: ${DATA_HOME}/backup

visit:
  address: http://192.168.10.7:8090











