app:
  name: xcode

APP_HOME: ${APP_HOME}
application: xcode

server:
  port: 8090

spring:
  freemarker:
    checkTemplateLocation: false

xcode:
  ssh:
    port: 10000
    key: tiklab-xcode-starter\src\main\resources\file\id_rsa
  file: tiklab-xcode-starter\src\main\resources\file

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_xcode?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  embbed:
    enable: false
  database: tiklab_xcode

#plugin config
PROJECT_HOME: ${user.home}/xcode/${app.name}
plugin:
  path: ${PROJECT_HOME}/plugin

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${PROJECT_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: false
    mode: server
    port: 5000
    datapath: ${PROJECT_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${PROJECT_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

datapath: ${PROJECT_HOME}/caches

message:
  sms:
    enabled: true

eas:
  embbed:
    enable: true
#    enable: false
#  address: http://192.168.10.14:8080
#  web:
#    address: http://192.168.10.14:3003

base:
  url: http://eas-ce.dev.tiklab.net



#homes
homes:
  address: http://192.168.10.7:8080

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.dev.tiklab.net

repository:
  code: xcode
  address: "http://192.168.10.7:8090"












