app:
  name: xcode

APP_HOME: ${APP_HOME}
application: xcode

server:
  port: 8080

xcode:
  ssh:
    port: 10000
    key: tiklab-xcode-starter\src\main\resources\file\id_rsa
  file: tiklab-xcode-starter\src\main\resources\file


jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.12.1.10:5432/tiklab_xcode?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  embbed:
    enable: false
  database: tiklab_xcode

#plugin config
DATA_HOME: /opt/tiklab/${app.name}
plugin:
  path: ${DATA_HOME}/plugin

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: true
    port: 5020
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5020
    group: g1
    database: dcs1
    expire: 7200

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

datapath: ${DATA_HOME}/caches

eas:
  embbed:
    enable: false
  address:  http://eas-ce.demo.tiklab.net


base:
  url: http://eas-ce.demo.tiklab.net

message:
  sms:
    enabled: true

#homes
homes:
  address: http://192.168.10.19:8080

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.dev.tiklab.net



repository:
  address: ${DATA_HOME}/repository

backup:
  address: ${DATA_HOME}/backup

visit:
  address: http://xcode-ce.demo.tiklab.net







