app:
  name: tiklab-xcode

APP_HOME: ${APP_HOME}
application: xcode

server:
  port: 8080

xcode:
  ssh:
    port: 10000
    key: tiklab-xcode-starter\src\main\resources\file\id_rsa
  file: tiklab-xcode-starter\src\main\resources\file


jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/xcode?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  embbed:
    enable: true
  database: xcode
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

eas:
  embbed:
    enable: false
  address:  http://eas-ce.demo.tiklab.net

#plugin config
DATA_HOME: /opt/tiklab/xcode
plugin:
  path: ${DATA_HOME}/plugin

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: false
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

datapath: ${DATA_HOME}/caches




base:
  url: http://eas-ce.demo.tiklab.net

message:
  sms:
    enabled: true

#homes
homes:
  address: http://192.168.10.19:8080

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.dev.tiklab.net



repository:
  address: ${DATA_HOME}/repository

backup:
  address:  /opt/tiklab/xcode-backups
  time: 0 0 2 * * ?
visit:
  address: http://xcode-ce.demo.tiklab.net







